### ISSUE TITLE
你好请问你这里有Swift的使用方法吗

### ISSUE THREAD

**Issue by CheungTieZhu** [udesk/UdeskSDK-iOS#15]

**Comment by xushichen** [comment]
import UdeskSDK

//初始化
let organization = UdeskOrganization.init(domain: "xx", appKey: "xx", appId: "xx")
let customer = UdeskCustomer.init()
customer.sdkToken = "TestSdkToken"
UdeskManager.initWith(organization, customer: customer)
        
//进入sdk
let sdkManager = UdeskSDKManager.init(sdkStyle: UdeskSDKStyle.default())
sdkManager?.pushUdesk(in: self, completion: nil)
