### ISSUE TITLE
版本从3.8.5倒退回3.8.2?

### ISSUE THREAD

**Issue by wiilen** [udesk/UdeskSDK-iOS#17]
今天pod install，发现podfile.lock里面存的是3.8.5的版本，但是直接搜索pod的版本却是3.8.2，要回退功能不能往前加版本非要回退吗？

**Comment by xushichen** [comment]
最新版本是3.8.6
先pod repo update再pod update

**Comment by wiilen** [comment]
谢谢，不好意思
