### ISSUE TITLE
能否开启对 bitcode 的支持？

### ISSUE THREAD

**Issue by c0ming** [udesk/UdeskSDK-iOS#2]
能否开启对 bitcode 的支持？

ld: bitcode bundle could not be generated because '/xxx/Pods/UdeskSDK/UdeskSDK/SDK/libUdesk.a(UDReachability.o)' was built **without full bitcode**. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64

如何开启可以参考：http://stackoverflow.com/a/31346742/544265

**Comment by xushichen** [comment]
支持bitcode

**Comment by c0ming** [comment]
@xushichen 只是 Enable Bitcode 为 YES 是不够的，生成的不是 full bitcode，还要在 Other C Flags 加上 -fembed-bitcode。验证是不是加上了可以执行命令 otool -l libFullBitcode.a | grep bitcode，有输出才是算支持了。

**Comment by xushichen** [comment]
@c0ming 已经支持了

**Comment by c0ming** [comment]
@xushichen 知道问题了，我的pod太久没更新，没指定版本号下载了旧版本的了。
