### ISSUE TITLE
-[NSNull(UdeskNullSafe) methodSignatureForSelector:] (UdeskNullSafe.m:120)

### ISSUE THREAD

**Issue by WeiQiZhang** [udesk/UdeskSDK-iOS#20]
开发者你好，我们接入3.9.2时，在iOS12时遇到这个必现的崩溃
出错栈堆：
#0 Thread
NSInvalidArgumentException
+[NSMethodSignature signatureWithObjCTypes:]: type signature is empty.
崩溃位置：
-[NSNull(UdeskNullSafe) methodSignatureForSelector:] (UdeskNullSafe.m:120)

**Comment by xushichen** [comment]
你好，方便加下我qq吗？
573979861

**Comment by WeiQiZhang** [comment]
好的！！
