### ISSUE TITLE
NSInternalInconsistencyException crash

### ISSUE THREAD

**Issue by wm219** [udesk/UdeskSDK-iOS#21]
UdeskSDK version：3.9.1

看到bugly日志如下：  
NSInternalInconsistencyException

UITableView (<UdeskMessageTableView: 0x10c220600; baseClass = UITableView; frame = (0 0; 375 603); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x1d06467b0>; animations = { bounds.origin=<CASpringAnimation: 0x1d463cc00>; bounds.size=<CASpringAnimation: 0x1d463cbe0>; }; layer = <CALayer: 0x1d063a540>; contentOffset: {0, 2389}; contentSize: {375, 2696}; adjustedContentInset: {0, 0, 296, 0}>) failed to obtain a cell from its dataSource (<UdeskChatViewController: 0x10da4b0f0>)

![image](https://user-images.githubusercontent.com/17446425/42752007-26c6bfde-891f-11e8-9dea-acc333a49f76.png)

不知当前最新版本是否已经解决这个问题？

**Comment by xushichen** [comment]
这个问题已经在3.9.2版本中解决。
目前最新版本是4.0.1，4.0.1版本相较于3.9.2有较大改动。
你可以根据自身需求更新。

**Comment by wm219** [comment]
👌
