### ISSUE TITLE
4.0.3 SDK进入聊天界面未发消息前，title显示null。请问这个问题在之后的版本优化了吗？

### ISSUE THREAD

**Issue by wm219** [udesk/UdeskSDK-iOS#23]
![image](https://user-images.githubusercontent.com/17446425/44502835-ed9c1f00-a6c5-11e8-8dc2-b26df3edb9e6.png)

**Comment by xushichen** [comment]
你好，这个应该是无消息对话过滤的标题，你可以在后台配置修改。
也可以加下我的qq：573979861
