### ISSUE TITLE
关于 预发 卡片消息  

### ISSUE THREAD

**Issue by Alexs321** [udesk/UdeskSDK-iOS#26]
大哥 你们能不能把那个 发送卡片的消息 加进预发消息的枚举里去 或者 把那个检测连接客服状态的 方法改成 公有的。。放在chatVC 现在用的好坎坷
自定义push chatVC 然后 延时发送的时候 经常会没检测完客服状态  消息发不出去 还会有两个Alert

**Comment by xushichen** [comment]
可以增加一个自定义按钮，点击自定义按钮才发送卡片消息。
自定义按钮会检查客服状态。
