### ISSUE TITLE
pod 安装后无法使用，改用拖进项目可以

### ISSUE THREAD

**Issue by x0806485** [udesk/UdeskSDK-iOS#28]
控制台报错信息：
objc[353]: Class UDURLConnectionOperation is implemented in both /private/var/containers/Bundle/Application/202329CF-07A8-42BB-B631-169EA5F90CE3/OrangeStage.app/Frameworks/UdeskSDK.framework/UdeskSDK (0x104bf3060) and /var/containers/Bundle/Application/202329CF-07A8-42BB-B631-169EA5F90CE3/OrangeStage.app/OrangeStage (0x103a49318). One of the two will be used. Which one is undefined.
objc[353]: Class UdeskMsgManager is implemented in both /private/var/containers/Bundle/Application/202329CF-07A8-42BB-B631-169EA5F90CE3/OrangeStage.app/Frameworks/UdeskSDK.framework/UdeskSDK (0x104bf30d8) and /var/containers/Bundle/Application/202329CF-07A8-42BB-B631-169EA5F90CE3/OrangeStage.app/OrangeStage (0x103a49390). One of the two will be used. Which one is undefined.
objc[353]: Class UdeskFMDatabaseQueue is implemented in both /private/var/containers/Bundle/Application/202329CF-07A8-42BB-B631-169EA5F90CE3/OrangeStage.app/Frameworks/UdeskSDK.framework/UdeskSDK (0x104bf3100) and /var/containers/Bundle/Application/202329CF-07A8-42BB-B631-169EA5F90CE3/OrangeStage.app/OrangeStage (0x103a493b8). One of the two will be used. Which one is undefined.

目前验证过的是，pod单装udesk是没有问题的，状态其他库就出问题。

**Comment by xushichen** [comment]
建议彻底删掉项目里的pod，之后再重新安装。

**Comment by CNJXFCjack** [comment]
same issues， 貌似从Xcode 10.0 开始这样。。在Xcode 9.0时编译无问题。
