### ISSUE TITLE
使用cocoapods安装后还是报错，没有添加上依赖库，手动加入之后依然报错

### ISSUE THREAD

**Issue by CoderLuYu** [udesk/UdeskSDK-iOS#3]
使用cocoapods安装后还是报错，没有添加上依赖库，手动加入之后依然报错。

**Comment by xushichen** [comment]
具体报什么错误呢？

**Comment by CoderLuYu** [comment]
又试了一次，只有在Podfile里使用
`use_frameworks!`
时才出错，并且是调用了初始化方法时才出错
`[UdeskManager initWithAppkey:@"公司密钥" domianName:@"公司域名"];`
错误信息
`Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_UdeskManager", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

![error](https://cl.ly/0J0r132i3x2y/Image%202016-08-25%20at%2019.18.15.png)

**Comment by xushichen** [comment]
你是pod UdeskSDK  还是 pod Udesk

**Comment by CoderLuYu** [comment]
就是本项目下的pod， pod 'UdeskSDK'

**Comment by xushichen** [comment]
我这测试了没问题啊，你加我QQ 573979861
