### ISSUE TITLE
获取后台SDK配置没有触发任何回调

### ISSUE THREAD

**Issue by akagongli** [udesk/UdeskSDK-iOS#31]
根据后台配置进入UdeskSDK IM相关页面时,SDK中会调用
+ (void)getServerSDKSetting:(void(^)(UdeskSetting *setting))success
                    failure:(void(^)(NSError *error))failure;
获取后台SDK配置,此方法既不触发成功回调,也没有失败的回调

**Comment by xushichen** [comment]
检查下Xcode控制台是否有输出UdeskSDK日志
控制台搜索关键字 “UdeskSDK”

**Comment by akagongli** [comment]
> 检查下Xcode控制台是否有输出UdeskSDK日志
> 控制台搜索关键字 “UdeskSDK”

整个获取SDK配置中,都没有UdeskSDK相关日志...

**Comment by xushichen** [comment]
你加我qq吧，573979861

**Comment by Juice007** [comment]
@akagongli @xushichen 想问下排查结果怎么样了？我今天也遇到这个问题

**Comment by Juice007** [comment]
发现问题了，代码加了一处判断导致没有走UDesk的注册方法
