### ISSUE TITLE
你们这SDK包也太大了

### ISSUE THREAD

**Issue by zhongyuanash** [udesk/UdeskSDK-iOS#32]
你们这SDK包也太大了，能不能弄小点，pods装半天...........真的很low，早知道不用你们公司的产品！

**Comment by xushichen** [comment]
先检查下你们访问git的网络。

文档里也有说明SDK大小的问题，你可以查看下。

你也可以使用手动安装的方式进行导入。

如果要用pods，建议更换默认的镜像，为git设置代理。

https://cloud.tencent.com/developer/article/1154014
https://segmentfault.com/q/1010000000118837

**Comment by xushichen** [comment]
5.x版本的sdk对整体包体积进行了优化，优化后总体包体积：37.3MB。

**Comment by wangguofeng-live** [comment]
同感SDK很大，用pods的体验酸爽

**Comment by Xuyadongfight** [comment]
现在5.x可以使用pods导入了吗

**Comment by wuxuezhen** [comment]
5.x能出一个正式版本吗，你们这版本管理很不规范

**Comment by ZHSY** [comment]
5.x 版本已经合并master，并支持pods。

**Comment by zhongyuanash** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
