### ISSUE TITLE
libxml/HTMLparser.h

### ISSUE THREAD

**Issue by zhangjiang1203** [udesk/UdeskSDK-iOS#33]
#include <libxml/HTMLparser.h>头文件查找不到，

**Comment by xushichen** [comment]
1.1 手动导入
Udesk SDK 的实现，依赖了一些系统框架，在开发应用时，需要在工程里加入这些框架。开发者首先点击工程右边的工程名,然后在工程名右边依次选择 TARGETS -> BuiLd Phases -> Link Binary With Libraries，展开 LinkBinary With Libraries 后点击展开后下面的 + 来添加下面的依赖项:

libz.tbd
libxml2.tbd
libresolv.tbd
libsqlite3.tbd
WebKit.framework
MapKit.framework
AssetsLibrary.framework
ImageIO.framework
Accelerate.framework
MediaPlayer.framework
Photos.framework
CoreText.framework
把下载的文件夹中的UdeskSDK文件夹拖到你的工程里，并进行以下配置

点击的你工程targets->Build Settings
搜索Other Linker Flags 加入 -lxml2 -ObjC
搜索header search paths 加入/usr/include/libxml2

看下这配置是否都完成。

**Comment by zhangjiang1203** [comment]
搜索header search paths 加入/usr/include/libxml2 这个现在要换成 ${SDK_DIR}/usr/include/libxml2才不报错
