### ISSUE TITLE
引入sdk的时候冲突太多，主要就是和YYImage类库的冲突

### ISSUE THREAD

**Issue by zhangjiang1203** [udesk/UdeskSDK-iOS#34]
主要就是和YYImage类库的冲突，图片和转换的方法，你们在所有引用的地方加上自己的前缀啊，不要加了一部分，这边还要手动处理

**Comment by xushichen** [comment]
贴下冲突错误

**Comment by zhangjiang1203** [comment]
在Udesk_YYImageCoder.m文件中
1246行 
 `  if(!YYCGImageDecodeToBitmapBufferWith32BitFormat(imageRef, &buffer, kCGImageAlphaLast | kCGBitmapByteOrderDefault)) return nil;`  
1380行
`    bytesPerRow = YYImageByteAlign(bitsPerPixel / 8 * canvasWidth, 32);
`
1419行
`    provider = CGDataProviderCreateWithData(destBytes, destBytes, destLength, YYCGDataProviderReleaseDataCallback);
`
2189行
`    provider = CGDataProviderCreateWithData(destBytes, destBytes, destLength, YYCGDataProviderReleaseDataCallback);
`

**Comment by xushichen** [comment]
应该是加完前缀没有测到webp的代码导致，加入webp框架后，udyy里的webp代码生效就报错了。

预计下周发版修复。

**Comment by xushichen** [comment]
已修复，下载最新版本sdk [4.3.0](https://github.com/udesk/UdeskSDK-iOS/releases/tag/4.3.0)
