### ISSUE TITLE
sdk中block中有很多属性引用会报警告，存在内存泄漏危险，这个期望下个版本更新处理一下

### ISSUE THREAD

**Issue by zhangjiang1203** [udesk/UdeskSDK-iOS#36]

**Comment by xushichen** [comment]
麻烦贴下代码

**Comment by zhangjiang1203** [comment]
`  UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Image/Udesk_YYAnimatedImageView.m:594:14: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
  UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Image/Udesk_YYAnimatedImageView.m:20:80: Expanded from macro 'LOCK'
  UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/DownloadManager/Udesk_WHC_HttpManager.m:167:14: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
  UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/DownloadManager/Udesk_WHC_HttpManager.m:168:14: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
  UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/DownloadManager/Udesk_WHC_HttpManager.m:169:14: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
  UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/DownloadManager/Udesk_WHC_HttpManager.m:170:14: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
  UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/DownloadManager/Udesk_WHC_DownloadOperation.m:215:84: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
  UdeskSDK5.1.0/UDChatMessage/UDTools/Util/UdeskVoiceRecord.m:92:13: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
  UdeskSDK5.1.0/UDChatMessage/UDTools/Util/UdeskVoiceRecord.m:230:14: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
  UdeskSDK5.1.0/UDChatMessage/UDTools/Util/UdeskVoiceRecord.m:232:40: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
  UdeskSDK5.1.0/UDChatMessage/UDTools/Util/UdeskVoiceRecord.m:234:18: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
  UdeskSDK5.1.0/UDChatMessage/UDTools/Util/UdeskVoiceRecord.m:249:21: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
  UdeskSDK5.1.0/UDChatMessage/UDTools/Util/UdeskVoiceRecord.m:250:21: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
  UdeskSDK5.1.0/UDChatMessage/UDTools/Util/UdeskVoiceRecord.m:257:25: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
  UdeskSDK5.1.0/UDChatMessage/UDTools/Util/UdeskVoiceRecord.m:258:25: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
  UdeskSDK5.1.0/UDChatMessage/UDIM/Views/Cells/General/UdeskVoiceCell.m:58:18: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
  UdeskSDK5.1.0/UDChatMessage/UDIM/Views/Cells/General/UdeskVoiceCell.m:60:17: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
  UdeskSDK5.1.0/UDChatMessage/UDIM/Views/Cells/General/UdeskVoiceCell.m:61:18: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior`
这只是一部分，还有很多

**Comment by zhangjiang1203** [comment]
`  /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Udesk_YYWebImageOperation.m:421:70: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
  /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Cache/Udesk_YYMemoryCache.m:439:30: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
  /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Udesk_YYImageCache.m:199:22: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
  /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Udesk_YYImageCache.m:209:33: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
  /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Udesk_YYImageCache.m:233:29: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
  /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Cache/Udesk_YYDiskCache.m:346:10: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
  /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Cache/Udesk_YYCache.m:89:29: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
  /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Cache/Udesk_YYCache.m:90:18: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
  /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Image/Udesk_YYAnimatedImageView.m:235:9: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
  /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Image/Udesk_YYAnimatedImageView.m:236:9: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
  /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Image/Udesk_YYAnimatedImageView.m:237:9: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
  /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Image/Udesk_YYAnimatedImageView.m:238:9: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
  /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Image/Udesk_YYAnimatedImageView.m:239:9: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
  /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Image/Udesk_YYAnimatedImageView.m:240:13: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
  /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Image/Udesk_YYAnimatedImageView.m:241:65: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
  /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Image/Udesk_YYAnimatedImageView.m:243:9: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
  /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Image/Udesk_YYAnimatedImageView.m:435:9: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
  /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Image/Udesk_YYAnimatedImageView.m:436:46: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
  /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Image/Udesk_YYAnimatedImageView.m:438:31: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior`

**Comment by zhangjiang1203** [comment]
/UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Udesk_YYWebImageOperation.m:421:70: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Cache/Udesk_YYMemoryCache.m:439:30: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Udesk_YYImageCache.m:199:22: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Udesk_YYImageCache.m:209:33: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Udesk_YYImageCache.m:233:29: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Cache/Udesk_YYDiskCache.m:346:10: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Cache/Udesk_YYCache.m:89:29: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Cache/Udesk_YYCache.m:90:18: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Image/Udesk_YYAnimatedImageView.m:235:9: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Image/Udesk_YYAnimatedImageView.m:236:9: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Image/Udesk_YYAnimatedImageView.m:237:9: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Image/Udesk_YYAnimatedImageView.m:238:9: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Image/Udesk_YYAnimatedImageView.m:239:9: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Image/Udesk_YYAnimatedImageView.m:240:13: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Image/Udesk_YYAnimatedImageView.m:241:65: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Image/Udesk_YYAnimatedImageView.m:243:9: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Image/Udesk_YYAnimatedImageView.m:435:9: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Image/Udesk_YYAnimatedImageView.m:436:46: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Image/Udesk_YYAnimatedImageView.m:438:31: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Udesk_YYWebImageOperation.m:372:52: 'initWithRequest:delegate:' is deprecated: first deprecated in iOS 9.0 - Use NSURLSession (see NSURLSession.h)
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Image/Udesk_YYImageCoder.m:2799:9: 'ALAssetsLibrary' is deprecated: first deprecated in iOS 9.0 - Use PHPhotoLibrary from the Photos framework instead
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/YYWebImage/Image/Udesk_YYImageCoder.m:2800:18: 'writeImageDataToSavedPhotosAlbum:metadata:completionBlock:' is deprecated: first deprecated in iOS 9.0 - Use creationRequestForAssetFromImageData: on PHAssetChangeRequest from the Photos framework to create a new asset instead
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/DownloadManager/Udesk_WHC_BaseOperation.m:40:55: 'CFURLCreateStringByAddingPercentEscapes' is deprecated: first deprecated in iOS 9.0 - Use [NSString stringByAddingPercentEncodingWithAllowedCharacters:] instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent (since each URL component or subcomponent has different rules for what characters are valid).
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/DownloadManager/Udesk_WHC_BaseOperation.m:105:58: 'initWithRequest:delegate:startImmediately:' is deprecated: first deprecated in iOS 9.0 - Use NSURLSession (see NSURLSession.h)
 /UdeskSDK5.1.0/UDChatMessage/UDIM/Views/Cells/General/UdeskVoiceCell.m:160:67: 'stringByAddingPercentEscapesUsingEncoding:' is deprecated: first deprecated in iOS 9.0 - Use -stringByAddingPercentEncodingWithAllowedCharacters: instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent since each URL component or subcomponent has different rules for what characters are valid.
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Util/UdeskVideoUtil.m:102:83: 'stringByAddingPercentEscapesUsingEncoding:' is deprecated: first deprecated in iOS 9.0 - Use -stringByAddingPercentEncodingWithAllowedCharacters: instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent since each URL component or subcomponent has different rules for what characters are valid.
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Util/UdeskVideoUtil.m:108:83: 'stringByAddingPercentEscapesUsingEncoding:' is deprecated: first deprecated in iOS 9.0 - Use -stringByAddingPercentEncodingWithAllowedCharacters: instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent since each URL component or subcomponent has different rules for what characters are valid.
 /UdeskSDK5.1.0/UDChatMessage/UDIM/Views/Cells/General/UdeskVideoCell.m:209:48: 'stringByAddingPercentEscapesUsingEncoding:' is deprecated: first deprecated in iOS 9.0 - Use -stringByAddingPercentEncodingWithAllowedCharacters: instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent since each URL component or subcomponent has different rules for what characters are valid.
 /UdeskSDK5.1.0/UDChatMessage/UDIM/Views/Cells/Robot/UdeskTopAskCell.m:124:20: 'stringByReplacingPercentEscapesUsingEncoding:' is deprecated: first deprecated in iOS 9.0 - Use -stringByRemovingPercentEncoding instead, which always uses the recommended UTF-8 encoding.
 /UdeskSDK5.1.0/UDChatMessage/UDIM/Views/Cells/General/UdeskTextCell.m:165:91: 'stringByAddingPercentEscapesUsingEncoding:' is deprecated: first deprecated in iOS 9.0 - Use -stringByAddingPercentEncodingWithAllowedCharacters: instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent since each URL component or subcomponent has different rules for what characters are valid.
 /UdeskSDK5.1.0/UDChatMessage/UDIM/Models/Messages/General/UdeskStructMessage.m:72:36: 'stringByAddingPercentEscapesUsingEncoding:' is deprecated: first deprecated in iOS 9.0 - Use -stringByAddingPercentEncodingWithAllowedCharacters: instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent since each URL component or subcomponent has different rules for what characters are valid.
 /UdeskSDK5.1.0/UDChatMessage/UDIM/Models/Messages/General/UdeskStructMessage.m:84:45: 'stringByAddingPercentEscapesUsingEncoding:' is deprecated: first deprecated in iOS 9.0 - Use -stringByAddingPercentEncodingWithAllowedCharacters: instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent since each URL component or subcomponent has different rules for what characters are valid.
 /UdeskSDK5.1.0/UDChatMessage/UDFAQ/Controller/UdeskSearchController.h:16:31: 'UISearchDisplayController' is deprecated: first deprecated in iOS 8.0 - UISearchDisplayController has been replaced with UISearchController
 /UdeskSDK5.1.0/UDChatMessage/UDFAQ/Controller/UdeskSearchController.m:96:49: 'UISearchDisplayController' is deprecated: first deprecated in iOS 8.0 - UISearchDisplayController has been replaced with UISearchController
 /UdeskSDK5.1.0/UDChatMessage/UDFAQ/Controller/UdeskSearchController.m:101:34: 'UISearchDisplayController' is deprecated: first deprecated in iOS 8.0 - UISearchDisplayController has been replaced with UISearchController
 /UdeskSDK5.1.0/UDChatMessage/UDFAQ/Controller/UdeskSearchController.m:66:68: 'UISearchDisplayController' is deprecated: first deprecated in iOS 8.0 - UISearchDisplayController has been replaced with UISearchController
 /UdeskSDK5.1.0/UDChatMessage/UDIM/Views/Cells/Robot/UdeskRichCell.m:135:20: 'stringByReplacingPercentEscapesUsingEncoding:' is deprecated: first deprecated in iOS 9.0 - Use -stringByRemovingPercentEncoding instead, which always uses the recommended UTF-8 encoding.
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Util/UdeskPrivacyUtil.m:20:26: 'ALAssetsLibrary' is deprecated: first deprecated in iOS 9.0 - Use PHPhotoLibrary from the Photos framework instead
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Util/UdeskPrivacyUtil.m:20:26: 'authorizationStatus' is deprecated: first deprecated in iOS 9.0 - Use authorizationStatus on the shared PHPhotoLibrary from the Photos framework instead
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Util/UdeskPrivacyUtil.m:20:50: 'ALAuthorizationStatusNotDetermined' is deprecated: first deprecated in iOS 9.0
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Util/UdeskPrivacyUtil.m:22:9: 'ALAssetsLibrary' is deprecated: first deprecated in iOS 9.0 - Use PHPhotoLibrary from the Photos framework instead
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Util/UdeskPrivacyUtil.m:24:49: 'ALAssetsGroupAll' is deprecated: first deprecated in iOS 9.0
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Util/UdeskPrivacyUtil.m:24:79: 'ALAssetsGroup' is deprecated: first deprecated in iOS 9.0 - Use PHAssetCollection from the Photos framework instead
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Util/UdeskPrivacyUtil.m:24:24: 'enumerateGroupsWithTypes:usingBlock:failureBlock:' is deprecated: first deprecated in iOS 9.0 - Use the PHFetchResult returned by one of the fetch... methods on PHAssetCollection from the Photos framework to enumerate asset collections instead
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Util/UdeskPrivacyUtil.m:51:31: 'ALAssetsLibrary' is deprecated: first deprecated in iOS 9.0 - Use PHPhotoLibrary from the Photos framework instead
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Util/UdeskPrivacyUtil.m:51:31: 'authorizationStatus' is deprecated: first deprecated in iOS 9.0 - Use authorizationStatus on the shared PHPhotoLibrary from the Photos framework instead
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Util/UdeskPrivacyUtil.m:51:55: 'ALAuthorizationStatusAuthorized' is deprecated: first deprecated in iOS 9.0
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Util/UdeskPrivacyUtil.m:57:30: 'ALAssetsLibrary' is deprecated: first deprecated in iOS 9.0 - Use PHPhotoLibrary from the Photos framework instead
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Util/UdeskPrivacyUtil.m:57:30: 'authorizationStatus' is deprecated: first deprecated in iOS 9.0 - Use authorizationStatus on the shared PHPhotoLibrary from the Photos framework instead
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Util/UdeskPrivacyUtil.m:57:54: 'ALAuthorizationStatusDenied' is deprecated: first deprecated in iOS 9.0
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/PhotoViewer/UdeskPhotoView.m:71:101: 'stringByAddingPercentEscapesUsingEncoding:' is deprecated: first deprecated in iOS 9.0 - Use -stringByAddingPercentEncodingWithAllowedCharacters: instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent since each URL component or subcomponent has different rules for what characters are valid.
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/PhotoViewer/UdeskOneScrollView.m:111:84: 'stringByAddingPercentEscapesUsingEncoding:' is deprecated: first deprecated in iOS 9.0 - Use -stringByAddingPercentEncodingWithAllowedCharacters: instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent since each URL component or subcomponent has different rules for what characters are valid.
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Vendors/PhotoViewer/UdeskOneScrollView.m:120:80: 'stringByAddingPercentEscapesUsingEncoding:' is deprecated: first deprecated in iOS 9.0 - Use -stringByAddingPercentEncodingWithAllowedCharacters: instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent since each URL component or subcomponent has different rules for what characters are valid.
 /UdeskSDK5.1.0/UDChatMessage/UDIM/Views/Cells/Robot/UdeskNewsCell.m:214:59: 'stringByAddingPercentEscapesUsingEncoding:' is deprecated: first deprecated in iOS 9.0 - Use -stringByAddingPercentEncodingWithAllowedCharacters: instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent since each URL component or subcomponent has different rules for what characters are valid.
 /UdeskSDK5.1.0/UDChatMessage/UDIM/Models/Messages/Robot/UdeskLinkMessage.m:51:54: 'stringByAddingPercentEscapesUsingEncoding:' is deprecated: first deprecated in iOS 9.0 - Use -stringByAddingPercentEncodingWithAllowedCharacters: instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent since each URL component or subcomponent has different rules for what characters are valid.
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Util/UdeskImagePicker.m:91:9: 'ALAssetsLibrary' is deprecated: first deprecated in iOS 9.0 - Use PHPhotoLibrary from the Photos framework instead
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Util/UdeskImagePicker.m:98:53: 'defaultRepresentation' is deprecated: first deprecated in iOS 9.0 - Use PHImageRequestOptions with the PHImageManager from the Photos framework instead
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Util/UdeskImagePicker.m:110:59: 'size' is deprecated: first deprecated in iOS 9.0 - Use requestImageDataForAsset:options:resultHandler: on PHImageManager to request image data for a PHAsset from the Photos framework instead
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Util/UdeskImagePicker.m:111:97: 'size' is deprecated: first deprecated in iOS 9.0 - Use requestImageDataForAsset:options:resultHandler: on PHImageManager to request image data for a PHAsset from the Photos framework instead
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Util/UdeskImagePicker.m:111:50: 'getBytes:fromOffset:length:error:' is deprecated: first deprecated in iOS 9.0 - Use requestImageDataForAsset:options:resultHandler: on PHImageManager to request image data for a PHAsset from the Photos framework instead
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Util/UdeskImagePicker.m:93:55: 'ALAsset' is deprecated: first deprecated in iOS 9.0 - Use PHAsset from the Photos framework instead
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Util/UdeskImagePicker.m:98:17: 'ALAssetRepresentation' is deprecated: first deprecated in iOS 9.0 - Use PHImageRequestOptions with the PHImageManager from the Photos framework instead
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Util/UdeskImagePicker.m:105:76: 'filename' is deprecated: first deprecated in iOS 9.0 - Use the Photos framework instead
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Util/UdeskImagePicker.m:132:23: 'assetForURL:resultBlock:failureBlock:' is deprecated: first deprecated in iOS 9.0 - Use fetchAssetsWithLocalIdentifiers:options: on PHAsset to fetch assets by local identifier (or to lookup PHAssets by a previously known ALAssetPropertyAssetURL use fetchAssetsWithALAssetURLs:options:) from the Photos framework instead
 /UdeskSDK5.1.0/UDChatMessage/UDIM/Views/Cells/General/UdeskImageCell.m:96:89: 'stringByAddingPercentEscapesUsingEncoding:' is deprecated: first deprecated in iOS 9.0 - Use -stringByAddingPercentEncodingWithAllowedCharacters: instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent since each URL component or subcomponent has different rules for what characters are valid.
 /UdeskSDK5.1.0/UDChatMessage/UDIM/Views/Cells/General/UdeskGoodsCell.m:79:108: 'stringByAddingPercentEscapesUsingEncoding:' is deprecated: first deprecated in iOS 9.0 - Use -stringByAddingPercentEncodingWithAllowedCharacters: instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent since each URL component or subcomponent has different rules for what characters are valid.
 /UdeskSDK5.1.0/UDChatMessage/UDIM/Views/Cells/UdeskBaseCell.m:177:100: 'stringByAddingPercentEscapesUsingEncoding:' is deprecated: first deprecated in iOS 9.0 - Use -stringByAddingPercentEncodingWithAllowedCharacters: instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent since each URL component or subcomponent has different rules for what characters are valid.
 /UdeskSDK5.1.0/UDChatMessage/UDTools/Category/NSAttributedString/NSAttributedString+UdeskHTML.m:295:45: 'stringByAddingPercentEscapesUsingEncoding:' is deprecated: first deprecated in iOS 9.0 - Use -stringByAddingPercentEncodingWithAllowedCharacters: instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent since each URL component or subcomponent has different rules for what characters are valid.

**Comment by xushichen** [comment]
看了几个，这几个都没有达到产生循环引用的必要条件，即：
1. block中引用了强引用的self
2. self也同时引用了block

有几个警告是sdk使用了 比项目设置的最低版本 还要低版本的API，sdk支持最低的版本是iOS7。

**Comment by zhangjiang1203** [comment]
是的  警告有点多😂
