### ISSUE TITLE
Demo运行报错

### ISSUE THREAD

**Issue by ApterKing** [udesk/UdeskSDK-iOS#39]
ndefined symbols for architecture arm64:
  "___isPlatformVersionAtLeast", referenced from:
      -[UdeskAFURLSessionManagerTaskDelegate initWithTask:] in libUdesk.a(UdeskAFURLSessionManager.o)
      -[UdeskAFURLSessionManagerTaskDelegate URLSession:task:didCompleteWithError:] in libUdesk.a(UdeskAFURLSessionManager.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by xushichen** [comment]
升级下Xcode到最新版本。

**Comment by ApterKing** [comment]
必须升级到最新版本吗？我们使用的第三方的一个库不能够将xcode升级到最新版本，因为涉及到Swift3.xx的

**Comment by ApterKing** [comment]
是否不升级到最新版本，这个Udesk 的SDK就不能够正常运行起来

**Comment by xushichen** [comment]
用Xcode10新编译了sdk，提交两个分支。

“4.x_xcode10” 分支对应的sdk版本是4.3.1。

“5.x_xocde10” 分支对应的sdk版本是5.1.1。

根据自身需求选择对应的分支。
