### ISSUE TITLE
建议移除 UIWebView 相关API的使用，苹果准备禁止使用UIWebView API的应用程序的提交

### ISSUE THREAD

**Issue by dong4255** [udesk/UdeskSDK-iOS#41]
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

**Comment by xushichen** [comment]
5.x版本的sdk已经移除了。
[5.x](https://github.com/udesk/UdeskSDK-iOS/tree/5.x)

**Comment by dong4255** [comment]
> 5.x版本的sdk已经移除了。
> [5.x](https://github.com/udesk/UdeskSDK-iOS/tree/5.x)

好的。感谢
