### ISSUE TITLE
Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread. 

### ISSUE THREAD

**Issue by ccrsno1** [udesk/UdeskSDK-iOS#43]
Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread.
(null)
((
	0   CoreFoundation                      0x000000018a48c980 DC2C95C6-B954-39E8-86A2-5E0AF8801E87 + 1255808
	1   libobjc.A.dylib                     0x000000018a1a5028 objc_exception_throw + 60
	2   Foundation                          0x000000018a9785e0 7A7A96AF-79E4-3DB1-8904-42E61CAE8999 + 2332128
	3   Foundation                          0x000000018a767828 7A7A96AF-79E4-3DB1-8904-42E61CAE8999 + 165928
	4   UIKitCore                           0x000000018e966250 AAFEFEBE-C172-3346-8972-810EB8F2F2C6 + 14795344
	5   UIKitCore                           0x000000018e967648 AAFEFEBE-C172-3346-8972-810EB8F2F2C6 + 14800456
	6   UIKitCore                           0x000000018dbbfd74 AAFEFEBE-C172-3346-8972-810EB8F2F2C6 + 482676
	7   UIKitCore                           0x000000018dbbb4b8 AAFEFEBE-C172-3346-8972-810EB8F2F2C6 + 464056
	8   UIKitCore                           0x000000018dbbb72c AAFEFEBE-C172-3346-8972-810EB8F2F2C6 + 464684
	9   UIKitCore                           0x000000018dbbba6c AAFEFEBE-C172-3346-8972-810EB8F2F2C6 + 465516
	10  UIKitCore                           0x000000018dbc0630 AAFEFEBE-C172-3346-8972-810EB8F2F2C6 + 484912
	11  UIKitCore                           0x000000018dbc0474 AAFEFEBE-C172-3346-8972-810EB8F2F2C6 + 484468
	12  UIKitCore                           0x000000018dba1364 AAFEFEBE-C172-3346-8972-810EB8F2F2C6 + 357220
	13  UIKitCore                           0x000000018df48a1c AAFEFEBE-C172-3346-8972-810EB8F2F2C6 + 4188700
	14  UIKitCore                           0x000000018df49104 AAFEFEBE-C172-3346-8972-810EB8F2F2C6 + 4190468
	15  UIKitCore                           0x000000018df5f214 AAFEFEBE-C172-3346-8972-810EB8F2F2C6 + 4280852
	16  UIKitCore                           0x000000018df57d08 AAFEFEBE-C172-3346-8972-810EB8F2F2C6 + 4250888
	17  UIKitCore                           0x000000018df5975c AAFEFEBE-C172-3346-8972-810EB8F2F2C6 + 4257628
	18  UIKitCore                           0x000000018df5bd0c AAFEFEBE-C172-3346-8972-810EB8F2F2C6 + 4267276
	19  UIKitCore                           0x000000018df5c270 AAFEFEBE-C172-3346-8972-810EB8F2F2C6 + 4268656
	20  UIKitCore                           0x000000018df5bc58 AAFEFEBE-C172-3346-8972-810EB8F2F2C6 + 4267096
	21  UIKitCore                           0x000000018df5beec AAFEFEBE-C172-3346-8972-810EB8F2F2C6 + 4267756
	22  xxx!__82-[UdeskAssetsPickerController fetchVideoDataWithSelectedModels:imagePicker:group:]_block_invoke [UdeskAssetsPickerController.m : 343]
	23  xxx!__68-[UdeskAssetsPickerManager fetchCompressVideoWithAssets:completion:]_block_invoke.80 [UdeskAssetsPickerManager.m : 167]
	24  xxx!__85-[UdeskAssetsPickerManager fetchVideoOutputPathWithAsset:presetName:success:failure:]_block_invoke [UdeskAssetsPickerManager.m : 189]
	25  Photos                              0x0000000195dc5950 7C38C43A-CB9B-3F72-8D0A-E4EF9D003F90 + 1870160
	26  Photos                              0x0000000195dc2988 7C38C43A-CB9B-3F72-8D0A-E4EF9D003F90 + 1857928
	27  libdispatch.dylib                   0x000000018a13e39c 0C7A69CD-F2EE-3426-BFD8-742C903D3D07 + 62364
	28  libdispatch.dylib                   0x000000018a131fd8 0C7A69CD-F2EE-3426-BFD8-742C903D3D07 + 12248
	29  libdispatch.dylib                   0x000000018a134758 0C7A69CD-F2EE-3426-BFD8-742C903D3D07 + 22360
	30  libdispatch.dylib                   0x000000018a133eb8 0C7A69CD-F2EE-3426-BFD8-742C903D3D07 + 20152
	31  libdispatch.dylib                   0x000000018a140bd4 0C7A69CD-F2EE-3426-BFD8-742C903D3D07 + 72660
	32  libdispatch.dylib                   0x000000018a141384 0C7A69CD-F2EE-3426-BFD8-742C903D3D07 + 74628
	33  libsystem_pthread.dylib             0x000000018a197690 _pthread_wqthread + 216
	34  libsystem_pthread.dylib             0x000000018a19d9e8 start_wqthread + 8
)

dSYM UUID: E4DC1F50-E886-3A27-8CF5-F1F46DCFB781
CPU Type: arm64
Slide Address: 0x0000000100000000
Binary Image:xxx
Base Address: 0x000000010413c000

**Comment by xushichen** [comment]
[https://github.com/udesk/UdeskSDK-iOS/commit/6e3e01144a3ade3358ec228a706a1af8471b464d](url)
我们在这个commit里修复了该问题，您可以更新至5.x分支的最新代码。

**Comment by ccrsno1** [comment]
ok
