### ISSUE TITLE
5.x 版本 pod 集成报错

### ISSUE THREAD

**Issue by xcuYao** [udesk/UdeskSDK-iOS#44]
由于5.x 版本 不支持pod 所以选择了如下方式集成
```
pod 'UdeskSDK', :git => 'git@github.com:udesk/UdeskSDK-iOS.git', :branch => '5.x'
```
 但是在遇到了报错
![](https://raw.githubusercontent.com/xcuYao/pic_repo/master/pic_go/WX20200713-120840.png)

移除
use_frameworks!
后 就不报错了
但是由于我的项目是swift项目 所以需要使用use_frameworks!

这里是我的示例demo  
https://github.com/xcuYao/UdeskErrorDemo.git

希望看到issues后可以解答一下～～ 非常感谢

**Comment by xushichen** [comment]
你可以先临时pod拉“dev_pod”这个分支的代码，该分支是基于5.x最新的代码。

正式版本会在后续上线”5.x“分支，之后也会考虑上传到pod上。

**Comment by xcuYao** [comment]
可以了 大概什么时候会合并到 5.x分支呢？
这个分支的代码 稳定吗？
主要是我想消除UIWebview的警告

**Comment by xushichen** [comment]
大概这周五或者下周会合并上线。

**Comment by xcuYao** [comment]
好的 🙏
