### ISSUE TITLE
ios 4.3.2 版本CocoaPods什么时候可以下载

### ISSUE THREAD

**Issue by yhrun** [udesk/UdeskSDK-iOS#46]
ios 4.3.2 版本CocoaPods什么时候可以下载

**Comment by yhrun** [comment]
@xushichen 我看到你们今天更新了 4.3.2 版本。预计什么时候上传CocoaPods

**Comment by xushichen** [comment]
4.3.2已经上传pod，执行下
$pod repo update
$pod install

**Comment by yhrun** [comment]
> 4.3.2已经上传pod，执行下
> $pod repo update
> $pod install

非常感谢，上午更新了。
