### ISSUE TITLE
4.3.2版無法通過編譯

### ISSUE THREAD

**Issue by charlie80124** [udesk/UdeskSDK-iOS#47]
Build input file cannot be found: '/Pods/UdeskSDK/UdeskSDK/UDChatMessage/UDFAQ/Controller/UdeskSearchController.m'

**Comment by charlie80124** [comment]
4.3.1版 push 後的返回按鍵, 有機率性的沒反應

**Comment by xushichen** [comment]
4.3.2版本中UdeskSearchController已经删除了。
您看下是否有缓存。执行下：
$pod cache clean UdeskSDK

删除之后执行
$pod repo update
$pod install

**Comment by charlie80124** [comment]
感謝回覆, 最後裝上了4.3.2版
但在返回案件上仍然有機率性的沒反應
最後查到  [UdeskSDKConfig customConfig].actionConfig.leaveUdeskSDKBlock 在判斷前離開了, 因此返回按鈕沒反應[Uploading 截圖 2020-08-12 13.35.04.png…]

**Comment by charlie80124** [comment]
感謝回覆
Push 或是 present 後, 返回鈕都有機率沒反應,  請問這個問題有解嗎?

**Comment by xushichen** [comment]
您指的是leaveUdeskSDKBlock这个bolck 在离开sdk页面的时候没响应吗？
你可以搜下这个block，断点看下这个bolck使用的地方。

**Comment by charlie80124** [comment]
最後發現如果如下宣告，會造成返回鍵有機率沒響應的情況，直接在需要展示Udesk服務時create，或是取消(!_udeskManager)判斷後表現就正常，在此做個註解
```
@property (nonatomic) UdeskSDKManager *udeskManager;
-(UdeskSDKManager *) udeskManager {
    if (!_udeskManager) {
        UdeskOrganization *organization = [[UdeskOrganization alloc]initWithDomain:UdeskDomain appKey:UdeskKey appId:UdeskID];
         
        UdeskCustomer* customer = [UdeskCustomer new];
        /...參數.../
        [UdeskManager initWithOrganization:organization customer:customer];

        _udeskManager = [[UdeskSDKManager alloc] initWithSDKStyle:[UdeskSDKStyle defaultStyle] sdkConfig:[UdeskSDKConfig customConfig]];
   }
    return _udeskManager;
}
```
