### ISSUE TITLE
在iOS14上发送图片显示蓝色，点击预览也是空白的。但是问了客服，又说是看到了图片。

### ISSUE THREAD

**Issue by yinanwang1** [udesk/UdeskSDK-iOS#48]
![DCIM(12)](https://user-images.githubusercontent.com/6257935/94555557-5a634980-028e-11eb-87e9-9f832735866f.jpg)
在iOS13上是没有问题的，只是在iOS14上有问题。

**Comment by JackSteven** [comment]
客服的电脑可以看到图片，但是客户端页面看不到图片，应该是iOS14兼容问题；

**Comment by xushichen** [comment]
我们近期会发布新版本优化，适配iOS14。

**Comment by yyny1789** [comment]
> 我们近期会发布新版本优化，适配iOS14。

5.x版本什么时候支持pod导入呢？

**Comment by fangasvsass** [comment]
4.3.3啥时候支持pod导入

**Comment by xushichen** [comment]
> > 我们近期会发布新版本优化，适配iOS14。
> 
> 5.x版本什么时候支持pod导入呢？

5.x版本可以使用以下命令pod导入
pod 'UdeskSDK', :git => 'https://github.com/udesk/UdeskSDK-iOS', :branch => '5.x'

**Comment by xushichen** [comment]
4.3.3  已发布到pod，执行以下命令更新
pod repo update
pod install
