### ISSUE TITLE
进入会话页面闪退

### ISSUE THREAD

**Issue by TonyGJJ** [udesk/UdeskSDK-iOS#50]
这是贵公司文档里面说的
APP使用百度地图，进入SDK会话页面直接崩溃，崩溃信息显示 "xmlFreeDoc"
出现这种情况，请检查使用的百度地图SDK版本是否是为3.4.2。请升级百度地图SDK到最新版本。

目前项目 里面 百度地图的SDK版本号是 6.0.0
UdskSDK 是直接Git 下来手动安装的 应该是5.x

**Comment by brookchenli** [comment]
请使用百度地图6.1.0. 这个是百度的问题，消失3年后的问题又出现了，我们接下来会看下怎么避开，有疑问可联系我们支持人员
