### ISSUE TITLE
4.3.3版本在iOS14系统下人工聊天图片无法显示

### ISSUE THREAD

**Issue by yuyangios** [udesk/UdeskSDK-iOS#53]
如题, 经测试4.3.3版本在iOS13下使用没有问题, [但是iOS14客户端无法显示图片(发送的图片和接收的图片都无法显示)]
![IMG_0685](https://user-images.githubusercontent.com/15159818/103876121-39708700-510e-11eb-96cf-a4c9c5169df3.PNG)麻烦大神们看到了抓紧给个回复

**Comment by xushichen** [comment]
GitHub上的Demo测试iOS14发送图片没有问题的。

检查下是否正确引入了4.3.3。
pod导入，执行下 pod repo update，再pod install。
手动导入，重新在GitHub下载最新版本，把工程里的udesk文件删除，之后按照文档重新导入下。

**Comment by yuyangios** [comment]
嗯, 问题找到了, 是我们集成错了, 由于某些原因我们线上版本仍然使用的是4.3.2版本. 切换成4.3.3就好了. 感谢
