### ISSUE TITLE
5.x 有版本获取离线的未读消息数吗

### ISSUE THREAD

**Issue by jinyaoye23** [udesk/UdeskSDK-iOS#55]
使用场景：
用户打开app后，不会打开udesk界面，只是在自己的app内操作，这时候需要读取未读消息数，并提示用户有n条未读消息，指引它打开udesk。

问题：
文档上没有看到获取离线的未读消息数接口，只有在线的未读消息数

期望：
希望sdk提供接口，方便读取用户的离线未读消息数量。

**Comment by ZHSY** [comment]
离线未读消息需要用户对接离线推送，自己维护未读数量可参考官网文档：https://www.udesk.cn/doc/ios/udesksdk_ios_im/#_11
