### ISSUE TITLE
Xcode 编译失败

### ISSUE THREAD

**Issue by luokuning** [udesk/UdeskSDK-iOS#56]
最近升级到了 Xcode 12.5，编译时一直报错：new is unavailable
<img width="550" alt="image" src="https://user-images.githubusercontent.com/12708534/116789575-0ea5a680-aae2-11eb-9239-03cae0c2ac68.png">

升级前使用 12.4 是 OK 的，Udesk SDK 版本为 4.3.1。

**Comment by sunkehappy** [comment]
老铁们，我看到已经修复了，啥时候发布？

**Comment by WuKong94** [comment]
同问什么时候可以修复

**Comment by WuKong94** [comment]
把new改成init可以临时用一下,等着发版本吧

**Comment by ZHSY** [comment]
最新master分支已经修复
