### ISSUE TITLE
连接中，系统繁忙

### ISSUE THREAD

**Issue by yasinn** [udesk/UdeskSDK-iOS#61]
安卓版本没问题。
iOS 从2.0升级到5.2.7了，也从手动集成切换成cocoapod了。编译通过，没有问题。但app一旦进入客服界面会出现这样
<img width="244" alt="截屏2022-09-28 下午4 11 51" src="https://user-images.githubusercontent.com/1224445/192725524-67d39722-bc85-4531-8d81-2f9bc0d80417.png">

这是Xcode console:
```
UdeskSDK：登录成功
UdeskSDK:Error Domain=https://域名.udesk.cn/udesk_im/sdk/v4/robots/init.json Code=9300 "(null)" UserInfo={message=服务器繁忙}
```
我找不到官方文档返回错误含义。

**Comment by ZHSY** [comment]
建议您反馈专属客服，提供相关账号信息 来协助解决
