### ISSUE TITLE
Xcode14打包，打开客服页面就会崩溃

### ISSUE THREAD

**Issue by gongshiwei** [udesk/UdeskSDK-iOS#62]

**Comment by gongshiwei** [comment]
5.2.8

**Comment by jackystd** [comment]
遇到同样的问题了，猜测是VOIP导致，望解决。
https://github.com/BelledonneCommunications/linphone-sdk/issues/250

**Comment by gongshiwei** [comment]
有人跟进吗

**Comment by ZHSY** [comment]
请使用5.2.8+版本

**Comment by ZHSY** [comment]
> 有人跟进吗
请使用5.2.8+版本

**Comment by ZHSY** [comment]
> 遇到同样的问题了，猜测是VOIP导致，望解决。 [BelledonneCommunications/linphone-sdk#250](https://github.com/BelledonneCommunications/linphone-sdk/issues/250)

请使用5.2.8+版本

**Comment by gongshiwei** [comment]
5.2.9？

**Comment by ZHSY** [comment]
> 5.2.9？

5.2.8也可以，如有问题可以提交工单反馈详细信息，会有专人跟进

**Comment by gongshiwei** [comment]
> > 5.2.9？
> 
> 5.2.8也可以，如有问题可以提交工单反馈详细信息，会有专人跟进

已经是5.2.8了，工单怎么提？

**Comment by ZHSY** [comment]
> > > 5.2.9？
> > 
> > 
> > 5.2.8也可以，如有问题可以提交工单反馈详细信息，会有专人跟进
> 
> 已经是5.2.8了，工单怎么提？

登录官网后台 提交 https://www.udesk.cn/

**Comment by gongshiwei** [comment]
这里不能直接跟你们开发者沟通吗，还要跑官网去提工单，真扯淡

**Comment by gongshiwei** [comment]
问题没解决为什么colse？

**Comment by ZHSY** [comment]
> 这里不能直接跟你们开发者沟通吗，还要跑官网去提工单，真扯淡

你提工单会有专人跟进，必要时也可直接跟开发人员沟通。github上响应不会总是那么及时。另外问题排查可能需要你们提供相关资料，不便在此直接留言。

**Comment by ZHSY** [comment]
> 这里不能直接跟你们开发者沟通吗，还要跑官网去提工单，真扯淡

你提工单会有专人跟进，必要时也可直接跟开发人员沟通。github上响应不会总是那么及时。另外问题排查可能需要你们提供相关资料，不便在此直接留言。
