### ISSUE TITLE
5.2.8，Xcode14，打开客服页面就会崩溃

### ISSUE THREAD

**Issue by gongshiwei** [udesk/UdeskSDK-iOS#63]
我不知道怎么提工单, 看demo吧
[testproject.zip](https://github.com/udesk/UdeskSDK-iOS/files/10053980/testproject.zip)

**Comment by gongshiwei** [comment]
有人看吗

**Comment by ZHSY** [comment]
你好，问题还有吗。我看一下你demo，工单可以在https://www.udesk.cn/提交

**Comment by ZHSY** [comment]
> 我不知道怎么提工单, 看demo吧 [testproject.zip](https://github.com/udesk/UdeskSDK-iOS/files/10053980/testproject.zip)

你的Podfile 虽然写了pod 'UdeskSDK', '5.2.8'。但是并没有真正install。 UdeskManager.sdkVersion(); 可以查看当前sdk版本。你当前是5.2.6
