### ISSUE TITLE
最新版本v5.2.9 历史聊天消息显示异常，点击跳转异常

### ISSUE THREAD

**Issue by qqcc1388** [udesk/UdeskSDK-iOS#64]
正常页面
【图片1】
![WX20221207-195142@2x](https://user-images.githubusercontent.com/11266874/206172996-bd36409b-05c6-4a07-8dcd-a0ea3db2f492.png)

历史消息中相同消息的内容显示异常，都挤在一起了
【图片2】
![1670413953128](https://user-images.githubusercontent.com/11266874/206173788-1e3b0267-0e21-4c29-a129-8bf368e60473.jpg)

历史消息显示样式异常，链接正常的情况下【图片1】是点击发送一条消息，在显示异常的样式中【图片2】，点击变成了打开一个webview页面，webview打开为空页面，这个问题希望能够得到解决

**Comment by qqcc1388** [comment]
新版本还会出现 图片无法打开  附件无法显示等问题

**Comment by ZHSY** [comment]
官网提交一下工单吧，会有专人跟进。github不常关注，沟通也不方便。

**Comment by qqcc1388** [comment]
sdk做的太差了，升级后很多功能都有问题，最后不得已改成直接用web版本的客服页面了
