### ISSUE TITLE
打包的时候报了bitcode错误

### ISSUE THREAD

**Issue by LuYu001** [udesk/UdeskSDK-iOS#9]
libUdesk.a(UDURLConnectionOperation.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

使用cocoapods安装的

**Comment by xushichen** [comment]
这个问题明天会上线一个小版本更新修复。

**Comment by xushichen** [comment]
@LuYu001  已经更新了，3.5.7
